name: Medusa Crush Recordings
favicon: null
layout_spectrum: 0.4012609359342605
typography_spectrum: 0.77764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12140f'
    - '#fafefd'
    - '#a5a4aa'
    - '#cfcdce'
    - '#383733'
  brandStrength: 0.3061675752978772
  lightness: 0.0625
  saturation: 0.8915250597056001
  rhythmicContrast: 1
purpose: []
