name: Medusa Crush Recordings
favicon: null
layout_spectrum: 0.4012609359342605
typography_spectrum: 0.88042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f8f7'
    - '#141a2a'
    - '#c8cede'
    - '#5f52bb'
    - '#7e869a'
  brandStrength: 0.3061675752978772
  lightness: 0.0625
  saturation: 0.8915250597056001
  rhythmicContrast: 1
purpose: []
